### ISSUE TITLE
There are two different dates on the website

### ISSUE THREAD

**Issue by pradyunsg** [PyconUK/2022.pyconuk.org#1]
FYI, since I think the date has changed from Oct -> Sept, but the images were not updated.

<img width="842" alt="Screenshot 2022-03-25 at 18 47 40" src="https://user-images.githubusercontent.com/3275593/160183007-e781f34f-3911-44b0-89c6-0e8fe47dc8ba.png">

**Comment by alexwlchan** [comment]
Thanks for spotting this! I’ve fixed it now, but missed there was an issue for it.
